### ISSUE TITLE
Better TS support

### ISSUE THREAD

**Issue by chriskrycho** [tracked-tools/tracked-built-ins#51]
In line with the proposal at emberjs/rfcs#730:

- [x] specify conformance (link to the as-yet un-finished RFC) – #313
- [x] define a support policy (should almost certainly be "simple majors") and specify it – #313
- [x] specify the supported TS versions and add type test coverage to CI – #313, #314
- [x] specify how this library defines "public API" (all exported type etc.)
- [x] set `strict: true` and `noPropertyAccessFromIndexSignature: true` in `tsconfig.json` – #315
